version: "3.8"
services:
  malinkundang:
    container_name: "malinkundang"
    image: "malinkundang:latest"
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        - fastapi-nano
    volumes:
        - .:/code
    ports:
      - 5000:5000
